name: macOS
on: [ push,pull_request ]
jobs:
  build-gcc:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GCC
        run: brew reinstall gcc ;gcc-11 -v
      - name: Prepare
        run: mkdir _build && cd _build && CC=gcc-11 cmake ..
      - name: Build
        run: cmake --build _build
      - name: List files
        run:
          ls -lRa
  build-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: mkdir _build && cd _build && CC=/usr/bin/clang cmake ..
      - name: Build
        run: cmake --build _build
      - name: List files
        run: ls -lRa